<a href="https://colab.research.google.com/github/darlinesther2006-bot/project/blob/main/project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files
import pandas as pd
uploaded=files.upload()
df=pd.read_csv('Sales_data.csv')
df.head()

Saving Sales_data.csv to Sales_data (1).csv

   Order_ID   Month     Product  Quantity   Amount Region
0         1   March     Monitor         2   3000.0  North
1         2  August  Headphones         8  24000.0   West
2         3   April      Laptop         8   4000.0   West
3         4    July     Monitor         1   3000.0   West
4         5     May      Webcam         4  10000.0  North

In [ ]:
df.rename(columns={
    'Order_ID':'OrderID'
}, inplace=True)

print("\n AFTER REMAINING")
print(df)

 AFTER REMAINING
     OrderID      Month     Product  Quantity   Amount Region
0          1      March     Monitor         2   3000.0  North
1          2     August  Headphones         8  24000.0   West
2          3      April      Laptop         8   4000.0   West
3          4       July     Monitor         1   3000.0   West
4          5        May      Webcam         4  10000.0  North
..       ...        ...         ...       ...      ...    ...
97        98  September      Webcam         8  24000.0  South
98        99      April    Keyboard         8  24000.0   West
99       100      April      Webcam         7  10500.0   East
100       21       July     Monitor         6  15000.0   East
101       41   November      Webcam         7   3500.0   East

[102 rows x 6 columns]

In [ ]:
df.dropna(subset=['Quantity'], inplace=True)
df.drop_duplicates(inplace=True)
df.reset_index(drop=True, inplace=True)
df

    OrderID      Month     Product  Quantity   Amount Region
0         1      March     Monitor         2   3000.0  North
1         2     August  Headphones         8  24000.0   West
2         3      April      Laptop         8   4000.0   West
3         4       July     Monitor         1   3000.0   West
4         5        May      Webcam         4  10000.0  North
..      ...        ...         ...       ...      ...    ...
95       96       July     Monitor         7   7000.0  North
96       97      April  Headphones         1   1000.0   East
97       98  September      Webcam         8  24000.0  South
98       99      April    Keyboard         8  24000.0   West
99      100      April      Webcam         7  10500.0   East

[100 rows x 6 columns]

In [ ]:
print("\n CLEANED DATASET")
print(df)

print("\n FINAL SHAPE:",df.shape)

 CLEANED DATASET
    OrderID      Month     Product  Quantity   Amount Region
0         1      March     Monitor         2   3000.0  North
1         2     August  Headphones         8  24000.0   West
2         3      April      Laptop         8   4000.0   West
3         4       July     Monitor         1   3000.0   West
4         5        May      Webcam         4  10000.0  North
..      ...        ...         ...       ...      ...    ...
95       96       July     Monitor         7   7000.0  North
96       97      April  Headphones         1   1000.0   East
97       98  September      Webcam         8  24000.0  South
98       99      April    Keyboard         8  24000.0   West
99      100      April      Webcam         7  10500.0   East

[100 rows x 6 columns]

 FINAL SHAPE: (100, 6)

In [ ]:
print(df.isnull().sum())

OrderID     0
Month       0
Product     1
Quantity    0
Amount      1
Region      0
dtype: int64

In [ ]:
df.dropna()

    OrderID      Month     Product  Quantity   Amount Region
0         1      March     Monitor         2   3000.0  North
1         2     August  Headphones         8  24000.0   West
2         3      April      Laptop         8   4000.0   West
3         4       July     Monitor         1   3000.0   West
4         5        May      Webcam         4  10000.0  North
..      ...        ...         ...       ...      ...    ...
95       96       July     Monitor         7   7000.0  North
96       97      April  Headphones         1   1000.0   East
97       98  September      Webcam         8  24000.0  South
98       99      April    Keyboard         8  24000.0   West
99      100      April      Webcam         7  10500.0   East

[98 rows x 6 columns]

In [ ]:

df["Amount"]=df["Amount"].fillna(df["Amount"].median())
print(df)

    OrderID      Month     Product  Quantity   Amount Region
0         1      March     Monitor         2   3000.0  North
1         2     August  Headphones         8  24000.0   West
2         3      April      Laptop         8   4000.0   West
3         4       July     Monitor         1   3000.0   West
4         5        May      Webcam         4  10000.0  North
..      ...        ...         ...       ...      ...    ...
95       96       July     Monitor         7   7000.0  North
96       97      April  Headphones         1   1000.0   East
97       98  September      Webcam         8  24000.0  South
98       99      April    Keyboard         8  24000.0   West
99      100      April      Webcam         7  10500.0   East

[100 rows x 6 columns]

In [ ]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
      ...
95    False
96    False
97    False
98    False
99    False
Length: 100, dtype: bool